# Generated by Django 5.1.3 on 2025-03-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(choices=[('Gardien', 'Gardien'), ('Défenseur', 'Défenseur'), ('Milieu', 'Milieu'), ('Attaquant', 'Attaquant')])),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurs', to='tournois_foot.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buts_equipe1', models.IntegerField(default=0)),
                ('buts_equipe2', models.IntegerField(default=0)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe1', to='tournois_foot.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe2', to='tournois_foot.equipe')),
            ],
        ),
    ]
