# Generated by Django 5.1.3 on 2025-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois_foot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='ville',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
