# Generated by Django 5.1.3 on 2025-03-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois_foot', '0002_equipe_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='buts_equipe1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='buts_equipe2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe2',
        ),
        migrations.AddField(
            model_name='equipe',
            name='buts_encaisses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipe',
            name='buts_marques',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipe',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='buts_domicile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='buts_exterieur',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='equipe_domicile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matchs_domicile', to='tournois_foot.equipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='equipe_exterieur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matchs_exterieur', to='tournois_foot.equipe'),
            preserve_default=False,
        ),
    ]
